version: '3'
services:
  tvtokyo:
    container_name: playfake
    build: .
    environment:
      - PORT=8081
      - MONGODB_PATH=mongodb://app_owner:app_owner@mongodb/tvtokyo
    working_dir: /usr/src/app/playfake
    command: /bin/bash startup.sh
    volumes:
    - .:/usr/src/app/playfake
    ports:
    - "4001:8081"